# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09129b4210e982ff679c4a086f0934863708d6f599eedd9ee7f4df658e3fab86c7baa37a91d016b5c03ee9bcf6ab62d1d782ba14e2a096f13af695285c1056e3

test:
  secret_key_base: 6a846452bfb969f60aa63408ab456d1db93bc67ea2d36e7203c59803bb882efa90afdf1a2fca66d0c451f85ede6b5fd9785eb95853a53bf502788d5bef69a5aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
